fix: remove decomissioned chains
WalletConnect/rpc-proxy pull request #140
Opened 2023-05-31 21:22 UTC by Rakowskiii

# Description

I was investigating why the tests are failing so oftenly, I though it was because half-baked system. Turns out Infura changed their handling of one decomissioned chain (from proper error to forbidden).

I think it's good idea to get rid of decomissioned chains. This way instead of giving strange error to user, we just inform them we don't support this chain with our message.

## How Has This Been Tested?

Ran tests.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-06-01 07:54 UTC, xDarksome commented
What's up with tests failing on ci?

2023-06-01 09:02 UTC, xDarksome requested changes

2023-06-01 09:02 UTC, xDarksome commented on src/lib.rs
> +    #[cfg(feature = "dynamic-weights")]
Why it's under a feature flag?

2023-06-01 09:02 UTC, xDarksome commented on src/lib.rs
> +            _ = updater => info!("Updater terminating")
Consider using https://docs.rs/futures/latest/futures/future/struct.OptionFuture.html to not duplice `select` macro

2023-06-01 09:07 UTC, Rakowskiii commented on src/lib.rs
> +    #[cfg(feature = "dynamic-weights")]
This dynamic-weights system will need to live for a while on staging before going to prod. 
The plan is to (for now) keep it as feature flag, and when confirmed working, we can remove the feature and just move it to main code

2023-06-01 09:27 UTC, Rakowskiii commented on src/lib.rs
> +            _ = updater => info!("Updater terminating")
@xDarksome if I do that, marking it as None when not using the "dynamic-weights" feature, it will quit instantly, as select waits for the first future to finish, and OptionFuture::None will finish instantly

2023-06-01 09:34 UTC, xDarksome commented on src/lib.rs
> +            _ = updater => info!("Updater terminating")
Ah, yea, we should use `join` instead anyway. As I mentioned before this is not a proper way to handle graceful shutdowns. But it would require a bit of refactoring plus this `updater` thing doesn't actually fit very well in the `join` concept.

Try https://docs.rs/futures/latest/futures/future/fn.select_all.html for now

2023-06-05 15:17 UTC, xDarksome approved these changes

2023-06-05 15:21 UTC, xDarksome commented
Look good, but fix the tests pls

2023-06-06 08:09 UTC, arein approved these changes
Which EVM testnets do we still support now?

2023-06-06 09:18 UTC, Rakowskiii commented
> Which EVM testnets do we still support now?

Ethereum Goerli
Optimist Goerli
Polygon Mumbai
Arbitrum goerli

This didn;t change thought. 
We had a route to some more, but they were decomissioned and would just just keep giving errors.

2023-06-06 10:07 UTC, merged