fix: adjust alarms
WalletConnect/rpc-proxy pull request #205
Opened 2023-06-26 10:41 UTC by Rakowskiii

# Description

Adjusting alarms to be more relevant and not trigger all the time, with no action to be taken.

Resolves #204 

## How Has This Been Tested?

Deployed to stating.

## Due Diligence

* [ ] Breaking change
* [ ] Requires a documentation update
* [ ] Requires a e2e/integration test update

2023-06-26 19:21 UTC, arein requested changes

2023-06-26 19:21 UTC, arein commented on terraform/monitoring/panels/ecs/availability.libsonnet
> +    ),
doesn't work unfortunately. Grafana doesn't allow to report on `expressions`.

2023-06-26 19:21 UTC, arein commented on terraform/monitoring/panels/proxy/errors_provider.libsonnet
> +      reducerType     = 'max',
why?

2023-06-27 08:50 UTC, Rakowskiii commented on terraform/monitoring/panels/proxy/errors_provider.libsonnet
> +      reducerType     = 'max',
The idea was to make alarms match the graphs (this evaluates every 1 min,so sometimes it alarms on value that's not graphed, which makes sense but has less clarity, I was wondering if we maybe want to instead change it to max and eventually decrease the value to trigger, but I might have misunderstood the way `max` works`) reverted to sum

2023-06-27 12:40 UTC, arein requested changes

2023-06-27 12:40 UTC, arein commented on terraform/monitoring/panels/proxy/errors_non_provider.libsonnet
> +      reducerType     = 'max',
`max` takes the `max` value from any host. We want `sum`

2023-06-27 12:40 UTC, arein commented on terraform/monitoring/panels/proxy/errors_provider.libsonnet
> +      reducerType     = 'max',
Forgot to revert?

2023-06-27 14:46 UTC, Rakowskiii commented on terraform/monitoring/panels/proxy/errors_provider.libsonnet
> +      reducerType     = 'max',
I didn't push 🤦  sorry

2023-06-28 09:05 UTC, arein approved these changes

2023-06-28 09:43 UTC, merged