feat: Add global redis for registry cache
WalletConnect/rpc-proxy pull request #36
Opened 2022-11-03 15:47 UTC by xav

2022-11-03 17:38 UTC, arein requested changes
Good stuff! Few changes requested

Do you know why `plan` is failing?

2022-11-03 17:38 UTC, arein commented on terraform/redis_replication/main.tf
> +  subnet_group_name             = aws_elasticache_subnet_group.private_subnets.name
we don't need this redis cluster to be globally replicated. When we regionalize it's simpler to just have one per region without global replication.
In the relay we have other state that actually needs to be replicated per region so it was convenient and already set up to do the same for the project cache.

2022-11-03 17:38 UTC, arein commented on terraform/redis_replication/main.tf
> +}
i know you're just copying this from the relay but nitpick can we not have one private hosted zone per redis? Can you set up a hosted zone for the RPC proxy instead? ideally you do this in the `infra` repository as the hosted zone will be shared when we regionalize the RPC

2022-11-03 17:39 UTC, arein reviewed
How did you test this?

2022-11-07 08:14 UTC, xav commented
> How did you test this?

This one is just for the infra, so `tf plan` basically.

2022-11-07 20:02 UTC, arein approved these changes

2022-11-07 20:09 UTC, arein commented
> > How did you test this?
> 
> This one is just for the infra, so `tf plan` basically.

We have `dev` and `staging` environments. Please feel free to test your changes on one or the other (ideally `dev`). The README has instructions.

2022-11-07 23:46 UTC, arein approved these changes
can you make a follow up task pls to also monitor Redis CPU/memory? We have an example in the relay monitoring logic

2022-11-08 11:11 UTC, xav commented on terraform/monitoring/main.tf
> +  #  )
I think it's been there a while but, without linting, it was invisible.
I'll remove it altogether.

2022-11-09 13:13 UTC, xav commented
> > > How did you test this?
> > 
> > 
> > This one is just for the infra, so `tf plan` basically.
> 
> We have `dev` and `staging` environments. Please feel free to test your changes on one or the other (ideally `dev`). The README has instructions.

Good thing you wanted to test it more thoroughly because the apply eventually failed.
I changed how the ECS containers are declared so that the JSON syntax can be checked instead of an opaque heredoc.

2022-11-09 13:14 UTC, merged